In [1]:
import sys
import os

# So notebooks can access src/
sys.path.append(os.path.abspath(".."))

In [2]:
import pandas as pd
import numpy as np
import random
from faker import Faker
from datetime import datetime
import os

In [3]:
fake = Faker()
random.seed(42)
np.random.seed(42)

NUM_PRODUCTS = 500
NUM_USERS = 2000

categories = ['Sofa', 'Chair', 'Table', 'Bed', 'Wardrobe']
materials = ['Wood', 'Metal', 'Glass', 'Fabric', 'Leather']
colors = ['Black', 'White', 'Grey', 'Brown', 'Beige', 'Blue']
styles = ['Modern', 'Contemporary', 'Vintage', 'Minimalist', 'Industrial']

os.makedirs("../data/raw", exist_ok=True)

In [4]:
products = []

for i in range(NUM_PRODUCTS):
    category = random.choice(categories)

    product = {
        "product_id": i,
        "name": f"{random.choice(styles)} {category}",
        "category": category,
        "material": random.choice(materials),
        "color": random.choice(colors),
        "style": random.choice(styles),
        "price": round(random.uniform(1000, 50000), 2),
        "rating": round(random.uniform(2.5, 5.0), 1),
    }

    product["description"] = f"{product['style']} {product['color']} {product['material']} {product['category']}"
    products.append(product)

products_df = pd.DataFrame(products)
products_df.to_csv("../data/raw/products.csv", index=False)

products_df.head()

,product_id,name,category,material,color,style,price,rating,description
0,0,Modern Sofa,Sofa,Glass,White,Contemporary,7837.36,2.8,Contemporary White Glass Sofa
1,1,Modern Wardrobe,Wardrobe,Leather,Brown,Modern,2460.06,3.0,Modern Brown Leather Wardrobe
2,2,Industrial Wardrobe,Wardrobe,Wood,Beige,Contemporary,36084.96,4.3,Contemporary Beige Wood Wardrobe
3,3,Contemporary Bed,Bed,Fabric,Beige,Vintage,40662.09,2.5,Vintage Beige Fabric Bed
4,4,Minimalist Chair,Chair,Glass,Grey,Contemporary,11550.37,4.4,Contemporary Grey Glass Chair

In [5]:
records = []

for user_id in range(NUM_USERS):
    for _ in range(random.randint(1, 10)):
        records.append({
            "user_id": user_id,
            "product_id": random.randint(0, NUM_PRODUCTS - 1),
            "event_type": random.choice(["view", "cart", "purchase"]),
            "timestamp": fake.date_time_between(start_date='-1y', end_date='now')
        })

behavior_df = pd.DataFrame(records)
behavior_df.to_csv("../data/raw/user_behavior.csv", index=False)

behavior_df.head()

   user_id  product_id event_type           timestamp
0        0         114   purchase 2026-01-01 20:46:35
1        0         301       view 2025-05-26 06:28:10
2        0         193       cart 2025-11-18 08:23:53
3        0         375   purchase 2025-07-23 13:05:30
4        0         150       view 2025-04-26 14:39:10